### ISSUE TITLE
Can you upgrade to fit Julia v1.5? 

### ISSUE THREAD

**Issue by zsz00** [000Justin000/GraphSAGE#1]
Can you upgrade to fit Julia v1.5/1.6?

**Comment by 000Justin000** [comment]
It should work with Julia v1.5, as long as the Flux version is 0.9. Do you have an example where it fails? If so, I can help look into this.

**Comment by zsz00** [comment]
ok,, my Flux version is 0.11, I will try the Flux 0.9.

**Comment by 000Justin000** [comment]
close for now
